blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/quinnjr/docker-extension-aws#readme
    about: Check the documentation for usage instructions
  - name: Discussions
    url: https://github.com/quinnjr/docker-extension-aws/discussions
    about: Ask questions and discuss with the community
